name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Cache node_modules to speed up dependency installation
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Cache the Next.js build cache
      - name: Cache Next.js build cache
        uses: actions/cache@v4
        id: nextjs-cache
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Enable Corepack (for Yarn 4+)
        run: corepack enable

      - name: Set Yarn to 4.x
        run: corepack prepare yarn@stable --activate

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build the project
        if: steps.nextjs-cache.outputs.cache-hit != 'true'
        run: yarn build
        env:
          NODE_ENV: "development"

      - name: Deploy to gh-pages branch
        run: |
          cd out
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Stage deploy for $GITHUB_REF"

          # Force push to the gh-pages branch of your production repo
          git push --force "https://x-access-token:${{ secrets.PRODUCTION_PAT }}@github.com/cdracars/stage.cola.games.git" HEAD:gh-pages
